name: Deploy to cPanel via FTP

on:
    push:
        branches:
            - main
jobs:
    web-deploy:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: Get latest code
              uses: actions/checkout@v2.3.2

            - name: Sync file
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                  server: ${{secrets.Demouhu_SERVER }}
                  username: ${{secrets.Demouhu_USERNAME }}
                  password: ${{secrets.Demouhu_PASSWORD }}
